Support to retransmit message
omec-project/gnbsim pull request #128
Opened 2024-01-26 15:07 UTC by thakurajayL

Supporting service request message retransmission
This is required when we evaluate 5G core network functon for redundancy events

2024-01-29 16:28 UTC, gab-arrobo commented
@thakurajayL, please resolve conflict

2024-01-30 17:06 UTC, thakurajayL commented on profile/context/profile.go
> +	profile.RetransMsg = false
Profile 4 is service req and I want to make sure all other profiles have retransMsg is set to false.

2024-01-30 17:09 UTC, gab-arrobo commented on profile/context/profile.go
> +	profile.RetransMsg = false
The thing is that with this line, you are also changing `profile4` to `false` regardless of what the user has configured for this profile

2024-01-30 21:51 UTC, thakurajayL commented on profile/context/profile.go
> +	profile.RetransMsg = false
Understood.. Fixed.

2024-01-30 22:31 UTC, gab-arrobo requested changes

2024-01-30 22:31 UTC, gab-arrobo commented on profile/context/profile.go
> +	RetransMsg     bool           `yaml:"retransMsg" json: "retransMsg"`
```suggestion
	RetransMsg     bool           `yaml:"retransMsg" json:"retransMsg"`
```

2024-01-31 00:38 UTC, gab-arrobo approved these changes
+1

2024-01-31 00:55 UTC, merged