Update README
omec-project/gnbsim pull request #160
Opened 2024-04-11 01:50 UTC by thakurajayL

2024-04-15 16:43 UTC, gab-arrobo requested changes

2024-04-15 16:43 UTC, gab-arrobo commented on README.md
> +    3gpp features for gNodeB Simulator
I think this should not have indentation (Take a look at the rendered markdown output)
```suggestion
   3gpp features for gNodeB Simulator
```

2024-04-15 23:18 UTC, thakurajayL commented on docs/README.md
> +  * [Configuration](./gnbsim_config.md)
We shall be adding more eventually.

2024-04-15 23:18 UTC, thakurajayL commented on docs/gnbsim_config.md
Agree. Will do the change.

2024-04-15 23:21 UTC, thakurajayL commented on README.md
> +The gnbsimF project welcomes new contributors. Feel free to propose a new feature or fix bugs!
Done.

2024-04-15 23:24 UTC, thakurajayL commented on docs/gnbsim_apis.md
> +    $ curl -i -X POST 127.0.0.1:6000/gnbsim/v1/executeProfile -H 'Content-Type: application/json' -d '{"profileType":"nwreqpdusessrelease","profileName":"profile8","enable":true,"gnbName":"gnb1","sta
Fixed.

2024-04-15 23:43 UTC, gab-arrobo commented on docs/config.md
> +## Enable or disable a specific profile using the "enable" field.
```suggestion
Enable or disable a specific profile using the "enable" field
```

2024-04-15 23:43 UTC, gab-arrobo commented on docs/config.md
> +## The config file for gNBSim can be found [here](../config/gnbsim.yaml)
```suggestion
The config file for gNBSim can be found [here](../config/gnbsim.yaml)
```

2024-04-15 23:43 UTC, gab-arrobo commented on docs/config.md
> +**1.register:**
```suggestion
Currently following profiles are supported :

**1.register:**
```

2024-04-16 03:45 UTC, gab-arrobo approved these changes
+1

2024-04-16 03:45 UTC, merged